name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  PROJECT_ID: heroic-throne-404808
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/heroic-throne-404808/sveltikit
  

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"
      - id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
  
      - name: "Docker auth"
        run: |
          IMAGE_TAG:${{ steps.vars.outputs.sha_short}}
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/sveltikit/sample:$IMAGE_TAG .
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/sveltikit/sample:$IMAGE_TAG
